AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'bin/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'db/schema.rb'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SingleArgumentDig:
  Exclude:
    - 'spec/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
