default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: <%= ENV.fetch('PG_DATABASE') { Rails.application.credentials[:pg][:database] } %>
  username: <%= ENV.fetch('PG_USERNAME') { Rails.application.credentials[:pg][:username] } %>
  password: <%= ENV.fetch('PG_PASSWORD') { Rails.application.credentials[:pg][:password] } %>
  host: <%= ENV.fetch('PG_HOST') { Rails.application.credentials[:pg][:host] } %>
  port: <%= ENV.fetch('PG_PORT') { Rails.application.credentials[:pg][:port] } %>

development:
  <<: *default
  database: example_development
test:
  <<: *default
  database: example_test
production:
  <<: *default
staging:
  <<: *default
github:
  <<: *default

